### ISSUE TITLE
Query for organisations and users seem not to work

### ISSUE THREAD

**Issue by MarvinKlar** [Asesjix/Zammad-Client#15]
Hey,

first of all I really appreciate your work with this API since there are no other .NET API's for Zammad.

In general the API works great for me, bu got issues searching for users and organisations. I didn't tested the other enitities.

In VB I created a `New ZammadAccount` with the base URL of my Zammad server and used the `ZammadAuthentication.Token` authentication.
Then I created a `OrganizationClient` by calling the `CreateOrganizationClient()` function on the `ZammadAccount` instance.
And when I try to search for an organisation like `SearchOrganizationAsync("Test", 1)` I receive an result containing all organizations of my Zammad server and not only the one which is called `Test`.

So, the query and limit seem not to work. I was wondering aboud that, cause when I try to query the organisation in my browser it works fine. When I call `https://[my Zammad server]/api/v1/organizations/search?query=Test&limit=1` I see the JSON string of the torganisation with the name `Test`.

Am I missing anything or is there any mistake?

Thank you very much for your help!

Thanks and regards
Marvin Klar

**Comment by Asesjix** [comment]
I think something with the query is not correct.
Will try to fix this evening.

**Comment by MarvinKlar** [comment]
When I now search for users or organizations I receive an empty result. But when I change the call
`return GetAsync<IList<User>>("/api/v1/users/search", $"?query={query}&limit={limit}&expand=true");` to
`return GetAsync<IList<User>>("/api/v1/users/search", $"query={query}&limit={limit}&expand=true");`
I receive the correct result. Why is this so?

**Comment by Asesjix** [comment]
Hm, it should not matter with or without the "?".
Can you please run the test below and tell me the result (success/fail)? The test tested exactly your scenario… 

https://github.com/Asesjix/Zammad-Client/blob/891fc9dd4f3560f93627a29999648fb72baeda92/test/Zammad.Client.Tests/Core/Protocol/HttpRequestBuilderTest.cs#L124-L125

https://github.com/Asesjix/Zammad-Client/blob/891fc9dd4f3560f93627a29999648fb72baeda92/test/Zammad.Client.Tests/Core/Protocol/HttpRequestBuilderTest.cs#L122-L136

**Comment by MarvinKlar** [comment]
This is the result of all tests: http://prntscr.com/jp848l

**Comment by Asesjix** [comment]
The integration test is failed while you not set the authentication in TestConstants.cs?
Witch version of zammad you use?
Tip: You can upload images direct to github 😉

**Comment by MarvinKlar** [comment]
No, I didn't set anything in the class TestConstants.cs
I use the latest version.

**Comment by Asesjix** [comment]
Can you set the authentication and try again?

**Comment by MarvinKlar** [comment]
Sure, I was unable to activate my account at `https://test.zammad.com` cause I didn't receive an activation email. So I got the following error for all tests with my unactivated account:
`Message: System.Net.Http.HttpRequestException : An error occurred while sending the request.`

But I also received the same error for all tests while testing with the credentails and URL of my own Zammad server.

**Comment by Asesjix** [comment]
Hm I think you have some other issue.

I checked the whole thing again UriBuilder does not care if the query with "?" is specified or not.
If not specified the UriBuilder set prefixed it automatically.

```

    public class UriBuilderTest
    {
        public const string Uri = "https://test.zammad.com/api/v1/organizations/search?query=test&limit=100&expand=true";

        [Fact]
        public void Test1()
        {
            var builder = new UriBuilder("https://test.zammad.com");
            builder.Path = "/api/v1/organizations/search";
            builder.Query = "?query=test&limit=100&expand=true";
            var uri = builder.Uri;
            Assert.Equal(Uri, uri.ToString());
        }

        [Fact]
        public void Test2()
        {
            var builder = new UriBuilder("https://test.zammad.com");
            builder.Path = "/api/v1/organizations/search";
            builder.Query = "query=test&limit=100&expand=true";
            var uri = builder.Uri;
            Assert.Equal(Uri, uri.ToString());
        }
    }

```

Can you debug the folling test?

https://github.com/Asesjix/Zammad-Client/blob/891fc9dd4f3560f93627a29999648fb72baeda92/test/Zammad.Client.IntegrationTests/OrganizationClientTest.cs#L96-L107

and check the RequestUri of the httpRequest at

https://github.com/Asesjix/Zammad-Client/blob/891fc9dd4f3560f93627a29999648fb72baeda92/src/Zammad.Client/Core/ZammadClient.cs#L50

and check the httpResponse before

https://github.com/Asesjix/Zammad-Client/blob/891fc9dd4f3560f93627a29999648fb72baeda92/src/Zammad.Client/Core/ZammadClient.cs#L51

Then you should get a detailed error and I can probably help you better.
I will also try to implement on the weekend something that helps in a fault analysis.

**Comment by Asesjix** [comment]
In [httpResponse.ReasonPhrase](https://docs.microsoft.com/de-de/dotnet/api/system.net.http.httpresponsemessage.reasonphrase?view=netframework-4.7.1#System_Net_Http_HttpResponseMessage_ReasonPhrase) should you find the error message.

**Comment by Asesjix** [comment]
@MarvinKlar could you find a error (message)?

**Comment by MarvinKlar** [comment]
I debugged this also in a project and noticed the following:
I do also get the same error as in the test:
![screenshot_3](https://user-images.githubusercontent.com/34421947/43638786-63a09570-971a-11e8-9afe-20ddd4e9cfe3.png)

And this is because the query string is broken (it contains two questionmarks):
![screenshot_4](https://user-images.githubusercontent.com/34421947/43638814-782d5794-971a-11e8-9407-5ac458ab30aa.png)

When you jump into the `UseQuery` function you can see that the query string gets appended:
![screenshot_6](https://user-images.githubusercontent.com/34421947/43638844-9374eb52-971a-11e8-9e9e-f695a13a077c.png)

And results in the following query string:
![screenshot_5](https://user-images.githubusercontent.com/34421947/43638856-9c0ac124-971a-11e8-91c0-54aa845a18e7.png)

But the point is, that the query string (e.g. `?query=B&limit=10&expand=true`) results in getting translated to `??query=B&limit=10&expand=true`. And this is because of the `UriBuilder`s implementation of the `Query` attribute, because this:
![screenshot_6](https://user-images.githubusercontent.com/34421947/43639106-6c623d70-971b-11e8-8ff5-4c83995abf57.png)

Gets translated to this:
![screenshot_8](https://user-images.githubusercontent.com/34421947/43639120-75e5bc50-971b-11e8-90f6-f063270e200d.png)

But it should be like this:
![screenshot_9](https://user-images.githubusercontent.com/34421947/43639135-843070a2-971b-11e8-8a82-3daebcfe6a3f.png)

So the result is correct:
![screenshot_10](https://user-images.githubusercontent.com/34421947/43639144-8cee8530-971b-11e8-9041-3e1b884056e5.png)

I hope you are able to fix this! This should be done by removing the questionmarks in the Client implementations. For the organizations it should be here:
https://github.com/Asesjix/Zammad-Client/blob/master/src/Zammad.Client/OrganizationClient.cs#L26
and here:
https://github.com/Asesjix/Zammad-Client/blob/master/src/Zammad.Client/OrganizationClient.cs#L31

**Comment by Asesjix** [comment]
I have no idea how you get the two question marks.
![image](https://user-images.githubusercontent.com/7798041/44060125-e2ec5170-9f53-11e8-897b-7179b01754e9.png)

**Comment by Asesjix** [comment]
For me it does not matter if a question mark is given or not, the uribuilder always does it right.
![image](https://user-images.githubusercontent.com/7798041/44060218-3cb272b6-9f54-11e8-9ce2-5eb7cddcb5c8.png)
