### ISSUE TITLE
Default values are not getting updated

### ISSUE THREAD

**Issue by MarvinKlar** [Asesjix/Zammad-Client#19]
If you want to change a value of e.g. an user back to the default value the JSON serializer removes this value and the values does not get changed:

https://github.com/Asesjix/Zammad-Client/blob/master/src/Zammad.Client/Core/Protocol/HttpRequestBuilder.cs#L125

Example:
You have a deactivated user and want to activate him again, you would update the user, but since the default value (active=false) gets removed when the object gets serialized, the value gets never updated.

Could you please fix this?

**Comment by Asesjix** [comment]
@MarvinKlar thank you for report this.
