### ISSUE TITLE
Creating ticket throws an Exception "Der Antwortstatuscode gibt keinen Erfolg an: 422 (Unprocessable Entity)."

### ISSUE THREAD

**Issue by mundza** [Asesjix/Zammad-Client#21]
Hello,

I am trying to create a ticket but I always get an Exeption 422

My method is

 `await ticketClient.CreateTicketAsync(
                new Ticket
                {
                    Title = "Help me!",
                    GroupId = 1,
                    CustomerId = 6,
                    PriorityId = 2,
                },
                new TicketArticle
                {
                   Subject = "Help me!!!",
                    Body = "Nothing Work!",
                    ContentType = "note",
               });`

and I do Wait() it :)

PS: I am using BasicAccount auth

thanks

**Comment by mundza** [comment]
I have all properties in "object" in settings -> system.. I have looked in your resources and all matches like customer_id is your JsonProp customer_id 

Dont know what to do ..

**Comment by mundza** [comment]
I have taken the source code and refactored to my needs.. now it is working .. imported 5k tickets with attachments and everything.. MarvinKlar you need to wait until task is finished.. I am using it like this.


`
                            Task thisTask = CreateTicket(ticketClient, ticketToInsert, ticketArticle);

                            while (!thisTask.IsCompleted)
                            {
                                Thread.Sleep(50);
                            }`

and the CreateTicket method is:

` public static async Task CreateTicket(TicketClient ticketClient, Ticket ticket, TicketArticle ticketArticle)
        {
            ticketCreated = await ticketClient.CreateTicketAsync(ticket, ticketArticle);
        }`

recheck your json.. make sure you dont send "null" values

**Comment by MarvinKlar** [comment]
Great to hear that! How do you set the attachements? I was unable to set them: https://github.com/Asesjix/Zammad-Client/issues/22

**Comment by Asesjix** [comment]
@mundza you have to set the Ticket.OwnerId, unfortunately I had forgotten in the readme.
If I may give you a hint, you're using the async pattern a bit "weird".

I think you're doing this because you're trying to sync the function?
```
Task thisTask = CreateTicket(ticketClient, ticketToInsert, ticketArticle);
while (!thisTask.IsCompleted)
{
   Thread.Sleep(50);
}
```
It would be better to do this:
```
var result = CreateTicket(ticketClient, ticketToInsert, ticketArticle).GetAwaiter().GetResult();
```

**Comment by mundza** [comment]
Yes I wanted to sync the function. Yours is also great and working.. 

btw: Also, with OwnerId it was not working.... there were some null values
