### ISSUE TITLE
Unable to set the data of a ticket attachment

### ISSUE THREAD

**Issue by MarvinKlar** [Asesjix/Zammad-Client#22]
The documentation sais, that you can set the `data` (content in base64) or the `attachments`: https://github.com/zammad/zammad-documentation/blob/master/api-ticket-article.rst#create

But I am only able to set the `Filename`, `Id` and `Preferences`:
![screenshot_1](https://user-images.githubusercontent.com/34421947/46077053-cdadbe80-c18f-11e8-97dd-24ca95dc7e4e.png)

How can I set the data?

**Comment by mundza** [comment]
![image](https://user-images.githubusercontent.com/16288189/46077235-6f351000-c190-11e8-9584-7a9955cc1d72.png)

this is why I downloaded source code.. so I can refactor code...
Add mime-type and data to your object like this

![image](https://user-images.githubusercontent.com/16288189/46077278-94298300-c190-11e8-9d16-f3430ac5645d.png)

**Comment by MarvinKlar** [comment]
Nice, can you please create a pull request containing your changes?

**Comment by mundza** [comment]
Thanks. Unfortunately no, it is integrated with the rest of my project so I cannot do it :) there are these comments they can read and apply :) Let me know if you need anything else

**Comment by MarvinKlar** [comment]
Okay, at least we do know now how to fix the issues. Thank you very much!

Now @Asesjix can implement the fixes. I can't wait for the update! :)

**Comment by MarvinKlar** [comment]
Created pull request https://github.com/Asesjix/Zammad-Client/pull/23

**Comment by Asesjix** [comment]
@mundza downloading the code and improving it and withholding it from the rest is not the best way ;-) The better way is to fork the project. Then the project owners (like me) can take over your improvements, which helps everyone (the open source thought).

**Comment by mundza** [comment]
I needed it very urgent, so I merged 2 projects together.. But I did told MarvinKlar what is the problem and how I fixed it :)
