### ISSUE TITLE
Give a more detailed error message than 422

### ISSUE THREAD

**Issue by MarvinKlar** [Asesjix/Zammad-Client#24]
I would be great to have a more detailed error message then the http status code 422. This could be done by reading the `HttpResponse` (as object) BEFORE calling `EnsureSuccessStatusCode()`. So you are able to have a look at the given error, instead of guessing, whats the issue.

**Comment by Asesjix** [comment]
This should help you 😜 

https://github.com/Asesjix/Zammad-Client/blob/5f7ced52c6624e0f9e46077eaaabec6cfc6dfc01/src/Zammad.Client/Core/ZammadClient.cs#L22-L33

https://github.com/Asesjix/Zammad-Client/blob/5f7ced52c6624e0f9e46077eaaabec6cfc6dfc01/src/Zammad.Client/Core/ZammadException.cs#L8-L30

**Comment by MarvinKlar** [comment]
How would i call this function in my production code?

**Comment by Asesjix** [comment]
In your exception handling, like this:

```
var account = TestHelper.CreateTestAccount();
var client = account.CreateTicketClient();
try
{
   var ticketSearch = await client.SearchTicketAsync("Zammad", 20);
}
catch(ZammadException e)
{
   // e.Request - contains the executed request
   // e.Response - contains the recived response
   await e.GetResponseContentAsStringAsync() 
}
```

**Comment by MarvinKlar** [comment]
Thanks!
