### ISSUE TITLE
Unable to create ticket without setting all values of a ticket

### ISSUE THREAD

**Issue by MarvinKlar** [Asesjix/Zammad-Client#25]
You are not able to create a ticket without setting all (not all, but at least very much) values of the `Ticket` object.

E.g. you have to set the `PriorityId`, `StateId`, `CreateArticleTypeId`, `CreateArticleSenderId`, `UpdatedById` and `CreatedById` because the don't support `null`-values.

Same for the `TicketArticle` with the values `SenderId`, `UpdatedById` and `CreatedById`.

Please support `Nullables` for these values.

**Comment by Asesjix** [comment]
Do not the values really have to be set?
![image](https://user-images.githubusercontent.com/7798041/46246168-917d9680-c3f9-11e8-891b-47ca3b821593.png)

**Comment by Asesjix** [comment]
I have tested this. you are right!
