### ISSUE TITLE
Can't receive any data

### ISSUE THREAD

**Issue by departet** [Asesjix/Zammad-Client#44]
Hey,
with following code i'm stuck at "client.GetTicketListAsync().Result". The code is running but it won't continue after this point. I have the same with user clients and the userlist. WinForms - .NET 4.7.2

```
var account = ZammadAccount.CreateTokenAccount("zammadpath", "token..");
var client = account.CreateTicketClient();
var liste = client.GetTicketListAsync().Result;
foreach(var t in liste)
{
Console.WriteLine(t.Title);
}
```
Some additional information:
API through browser works
API through curl works (with --insecure as my zammad instance has a self signed cert)
Zammad Version: 4.0.X

**Comment by Kleinrotti** [comment]
You have to use async/await. 
`client.GetTicketListAsync().Result;` will block the thread infinitely.
Try this instead:
`var liste = await client.GetTicketListAsync();`

**Comment by departet** [comment]
Argh basic c# mistake. Sorry for the inconvenience!

**Comment by departet** [comment]
Reopening this, can't use `await`.

> the await operator can only be used within an async method

EDIT: Another fault by me. Had to run this in an async method and not in the main thread. Don't be me level stupid.
