### ISSUE TITLE
Add support for 'X-On-Behalf-Of'-Header.

### ISSUE THREAD

**Issue by rolfschmidt** [Asesjix/Zammad-Client#9]
Hi,
there is a new feature which would be nice to get supported in the zammad apis:

issue:
https://github.com/zammad/zammad/issues/1805

documentation:
https://docs.zammad.org/en/latest/api-intro.html#example-curl-request-on-behalf-of-a-different-user

Best regards,
Rolf

**Comment by Asesjix** [comment]
You can use the feature like this:
`
var account = ZammadAccount.CreateBasicAccount(endpoint, user, password).UseOnBehalfOf("<MyUser-Id/Login/Email>");
`
